### ISSUE TITLE
Impossible to compile

### ISSUE THREAD

**Issue by pascualito2000** [xivSolutions/biggy#21]
I've downloaded the source code, but I can't compile it. I think that I'm making some mistake but I don't know what it is.

for instance this error : \biggy-master\src\Biggy.Core\bin\Debug\Biggy.dll

Any help?

Thanks a lot!!!

**Comment by xivSolutions** [comment]
You may need to enable Nuget package restore.

That error doesn't tell us enough-that just means the Biggy sol couldn't compile because of some other error further upstream, most likely due to missing Nuget packages.

Also, if you are not using the azure bits, you might want to exclude that project, and comment out the Azure test files.

**Comment by xivSolutions** [comment]
@pascualito2000  Did you get this to build on your machine?

**Comment by Lucas-S** [comment]
I can recreate this one, there are some doggy references in the project files - I have just made a pull request (i hope - first one ever) that should fix this

**Comment by pascualito2000** [comment]
Hi xivSolutions and thank you for your answer
Yes I've tried to compile it in my machine
I've configured to restore Nuget packages.

I'm still having the messages errors

for example:
cannot load the metadata file.... biggy-master\src\Biggy.Core\bin\Debug\Biggy.dll

I know that I'm making some mistakes, but I can't find out what it is....

I attach an image with references problems. I can't load these packages

![biggy_errors](https://cloud.githubusercontent.com/assets/7718234/5977356/f1232440-a875-11e4-8127-c6f51682621c.PNG)

Thanks a lot !!!
Javier.

**Comment by xivSolutions** [comment]
Hi All - 

Thanks for your feedback and patience on this. I am unfortunately on the road at the moment, but I will try to see what's up with this asap. 

@Lucas-S  - Thanks for the PR - I don't want to just merge it without seeing what the source of the issue was. Appreciate your patience and work on the issue, and will merge as soon as possible. :-)

@pascualito2000 - The two Mono dependencies don;t matter unless you are on Mono, but the other two look like an issue with Nuget. 

Can you try pulling down @Lucas-S changes, and see if this fixes the problem?

Sorry to do this this way, but...I'm at a funeral far from home atm.

**Comment by xivSolutions** [comment]
@pascualito2000 Try now. @Lucas-S PR should fix this. Not sure where those odd paths came from, possibly my Mono implementation?
